version: '3'
services:
  node-server:
    build: .
    ports:
      - "3000:3000"
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: db_patient_management_system
    ports:
      - "3307:3306" # ใช้เพื่อแมพพอร์ตของ MySQL บนโฮสต์
    volumes:
      - /data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306 # ใช้พอร์ต 3306 ภายใน container ของ MySQL
      PMA_USER: root
      PMA_PASSWORD: root  # ควรเป็นรหัสผ่านที่กำหนดใน MYSQL_ROOT_PASSWORD
    ports:
      - "8080:80"
    depends_on:
      - db




# version: '3'
# services:
#   mysql:
#     image: mysql:5.7
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: rootpassword
#       MYSQL_DATABASE: db_users
#     ports:
#       - "3307:3306"
#     networks:
#       - app-network


#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     restart: always
#     ports:
#       - "8080:80"
#     environment:
#       PMA_HOST: mysql
#       MYSQL_ROOT_PASSWORD: root
#     networks:
#       - app-network

#   nodejs:
#     build: .
#     restart: always
#     depends_on:
#       - mysql
#     environment:
#       DB_HOST: mysql
#       DB_USER: root
#       DB_PASSWORD: root
#       DB_NAME: db_users
#     ports:
#       - "3000:3000"
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge
